// Chaque entrée : une expression, son explication et une phrase d'exemple.
// Pour enrichir le carnet, il suffit d'ajouter un objet au tableau ci-dessous.
const EXPRESSIONS = [
  { expression: "Poser un lapin", explication: "Ne pas se présenter à un rendez-vous, sans prévenir la personne qui attend.", exemple: "Il m'a posé un lapin hier soir, je l'ai attendu une heure au café." },
  { expression: "Avoir le cafard", explication: "Être triste, un peu déprimé, sans raison précise.", exemple: "Depuis qu'il pleut sans arrêt, j'ai un peu le cafard." },
  { expression: "Casser du sucre sur le dos de quelqu'un", explication: "Dire du mal de quelqu'un en son absence.", exemple: "Arrête de casser du sucre sur son dos, ce n'est pas très correct." },
  { expression: "Chercher midi à quatorze heures", explication: "Compliquer inutilement une chose simple.", exemple: "Ne cherche pas midi à quatorze heures, la réponse est juste devant toi." },
  { expression: "Avoir un chat dans la gorge", explication: "Avoir la voix enrouée, avoir du mal à parler clairement.", exemple: "Excuse-moi, j'ai un chat dans la gorge ce matin." },
  { expression: "Filer à l'anglaise", explication: "Partir discrètement, sans dire au revoir à personne.", exemple: "Il a filé à l'anglaise avant la fin de la soirée." },
  { expression: "Mettre son grain de sel", explication: "Donner son avis sur un sujet sans qu'on le lui ait demandé.", exemple: "Il faut toujours qu'elle mette son grain de sel dans nos conversations." },
  { expression: "Coûter les yeux de la tête", explication: "Être extrêmement cher.", exemple: "Cette voiture coûte les yeux de la tête." },
  { expression: "Avoir la pêche", explication: "Être plein d'énergie, se sentir en pleine forme.", exemple: "Ce matin j'ai la pêche, j'ai vraiment bien dormi." },
  { expression: "Tomber dans les pommes", explication: "S'évanouir.", exemple: "Elle est tombée dans les pommes à cause de la chaleur." },
  { expression: "Raconter des salades", explication: "Mentir, inventer des histoires peu crédibles.", exemple: "Ne l'écoute pas, il raconte encore des salades." },
  { expression: "Avoir un poil dans la main", explication: "Être particulièrement paresseux.", exemple: "Il a un poil dans la main, il ne fait jamais rien à la maison." },
  { expression: "Donner sa langue au chat", explication: "Renoncer à deviner une réponse et demander qu'on la révèle.", exemple: "Je donne ma langue au chat, quelle est la réponse ?" },
  { expression: "Il pleut des cordes", explication: "Il pleut très fort, abondamment.", exemple: "Prends un parapluie, il pleut des cordes dehors." },
  { expression: "Avoir d'autres chats à fouetter", explication: "Avoir des préoccupations plus importantes ou plus urgentes.", exemple: "Je n'ai pas le temps de m'en occuper, j'ai d'autres chats à fouetter." },
  { expression: "Mettre la charrue avant les bœufs", explication: "Faire les choses dans le désordre, précipiter une étape avant l'autre.", exemple: "On ne peut pas signer avant d'avoir le budget, ce serait mettre la charrue avant les bœufs." },
  { expression: "Être dans de beaux draps", explication: "Se trouver dans une situation difficile ou embarrassante.", exemple: "Avec toutes ces dettes, il est dans de beaux draps." },
  { expression: "Avoir le bras long", explication: "Avoir de l'influence ou des relations utiles.", exemple: "Il a le bras long dans cette entreprise, il connaît tout le monde." },
  { expression: "Passer une nuit blanche", explication: "Ne pas dormir du tout pendant la nuit.", exemple: "J'ai passé une nuit blanche à réviser pour l'examen." },
  { expression: "Se prendre un râteau", explication: "Essuyer un refus, en particulier dans le domaine amoureux.", exemple: "Il lui a proposé de sortir avec lui, mais il s'est pris un râteau." },
  { expression: "Avoir la moutarde qui monte au nez", explication: "Commencer à s'énerver, sentir la colère arriver.", exemple: "Quand il a menti devant tout le monde, j'ai senti la moutarde me monter au nez." },
  { expression: "Rouler quelqu'un dans la farine", explication: "Tromper quelqu'un, le duper.", exemple: "Ce vendeur t'a roulé dans la farine avec ce prix." },
  { expression: "Ne pas être dans son assiette", explication: "Ne pas se sentir bien, physiquement ou moralement.", exemple: "Tu es pâle, tu n'as pas l'air dans ton assiette aujourd'hui." },
  { expression: "Avoir un coup de foudre", explication: "Tomber amoureux instantanément.", exemple: "Ils ont eu un coup de foudre en se rencontrant à la fac." },
  { expression: "Mettre les pieds dans le plat", explication: "Aborder un sujet délicat sans aucun tact.", exemple: "Il a encore mis les pieds dans le plat en posant cette question." },
  { expression: "Faire la grasse matinée", explication: "Dormir tard, prolonger la matinée au lit.", exemple: "Le dimanche, j'aime faire la grasse matinée." },
  { expression: "Avoir les yeux plus gros que le ventre", explication: "Se servir plus qu'on ne peut manger, ou être trop ambitieux.", exemple: "Il a pris trois desserts, il a vraiment les yeux plus gros que le ventre." },
  { expression: "Jeter l'éponge", explication: "Abandonner, renoncer à continuer.", exemple: "Après trois échecs, il a fini par jeter l'éponge." },
  { expression: "Ne pas y aller par quatre chemins", explication: "Être direct, franc, sans détour.", exemple: "Je ne vais pas y aller par quatre chemins : ton projet ne marche pas." },
  { expression: "Tirer les vers du nez", explication: "Faire parler quelqu'un par des questions habiles, lui soutirer des informations.", exemple: "Elle a réussi à lui tirer les vers du nez sur son secret." },
  { expression: "Être sur son trente-et-un", explication: "Être très élégamment habillé.", exemple: "Pour le mariage, elle était sur son trente-et-un." },
  { expression: "Avoir la tête dans les nuages", explication: "Être distrait, rêveur, peu attentif à la réalité.", exemple: "Concentre-toi un peu, tu as toujours la tête dans les nuages." },
  { expression: "Casser sa pipe", explication: "Mourir (registre familier).", exemple: "Le vieux chat du voisin a cassé sa pipe la semaine dernière." },
  { expression: "Mettre du beurre dans les épinards", explication: "Améliorer légèrement sa situation financière.", exemple: "Ce petit boulot du week-end met du beurre dans les épinards." },
  { expression: "Faire d'une pierre deux coups", explication: "Réaliser deux choses en une seule action.", exemple: "En allant au marché, j'ai fait d'une pierre deux coups : les courses et la promenade." },
  { expression: "Traîner des pieds", explication: "Agir avec réticence et lenteur, montrer peu d'enthousiasme.", exemple: "Il traîne des pieds pour rendre son rapport." },
  { expression: "Avoir le cœur sur la main", explication: "Être généreux, toujours prêt à aider les autres.", exemple: "Elle a le cœur sur la main, elle aide tout le monde sans compter." },
  { expression: "Passer l'éponge", explication: "Pardonner une faute, décider de l'oublier.", exemple: "Cette fois, je passe l'éponge, mais ne recommence pas." },
  { expression: "Se faire des cheveux blancs", explication: "Se faire beaucoup de souci pour quelqu'un ou quelque chose.", exemple: "Avec ses résultats scolaires, ses parents se font des cheveux blancs." },
  { expression: "Voir midi à sa porte", explication: "Juger toute chose selon son propre point de vue, sans considérer celui des autres.", exemple: "Il voit midi à sa porte, il ne comprend jamais le point de vue des autres." },
  { expression: "Être haut comme trois pommes", explication: "Être très petit, généralement en parlant d'un enfant.", exemple: "Il était haut comme trois pommes quand je l'ai connu." },
  { expression: "Avoir la banane", explication: "Sourire, être de bonne humeur.", exemple: "Elle a la banane depuis qu'elle a eu son diplôme." },
  { expression: "Manger sur le pouce", explication: "Manger rapidement, sans prendre le temps de s'installer.", exemple: "À midi, je mange souvent sur le pouce entre deux réunions." },
  { expression: "Avoir du pain sur la planche", explication: "Avoir beaucoup de travail à accomplir.", exemple: "Avant les vacances, j'ai encore du pain sur la planche." },
  { expression: "Faire la tête", explication: "Bouder, être de mauvaise humeur envers quelqu'un.", exemple: "Depuis notre dispute, il me fait la tête." },
  { expression: "Prendre ses jambes à son cou", explication: "S'enfuir en courant, très rapidement.", exemple: "En voyant le chien, il a pris ses jambes à son cou." },
  { expression: "Mettre la main à la pâte", explication: "Participer activement à une tâche, s'impliquer concrètement.", exemple: "Pour préparer le repas de famille, tout le monde met la main à la pâte." },
  { expression: "Avoir le compas dans l'œil", explication: "Évaluer une distance ou une mesure avec précision, sans instrument.", exemple: "Le menuisier a le compas dans l'œil, il ne se trompe presque jamais." },
  { expression: "Vendre la mèche", explication: "Révéler un secret que l'on devait garder.", exemple: "C'est lui qui a vendu la mèche à propos de la surprise." },
  { expression: "Faire chou blanc", explication: "Échouer complètement dans une tentative.", exemple: "On a cherché partout pendant des heures, on a fait chou blanc." },
];
