// Expressions et proverbes plus rares, moins couramment employés.
// Même structure que expressions-data.js : il suffit de remplacer ce
// fichier (ou son contenu) pour l'utiliser à la place sur le site.
const EXPRESSIONS = [
  { expression: "Tant va la cruche à l'eau qu'à la fin elle se casse", explication: "À force de s'exposer au danger ou de répéter un risque, on finit tôt ou tard par en subir les conséquences.", exemple: "Il conduit toujours trop vite ; tant va la cruche à l'eau qu'à la fin elle se casse." },
  { expression: "Il n'est pire eau que l'eau qui dort", explication: "Les personnes discrètes ou silencieuses peuvent être les plus redoutables, sous des dehors calmes.", exemple: "Méfie-toi de lui, il ne dit jamais rien, mais il n'est pire eau que l'eau qui dort." },
  { expression: "Faire des gorges chaudes de quelque chose", explication: "Se moquer ouvertement et sans retenue de quelque chose ou de quelqu'un.", exemple: "Toute l'équipe a fait des gorges chaudes de sa mésaventure." },
  { expression: "S'entendre comme larrons en foire", explication: "Bien s'entendre, être complices, souvent dans une intention peu recommandable.", exemple: "Ces deux-là s'entendent comme larrons en foire depuis leur rencontre." },
  { expression: "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué", explication: "Il ne faut pas se réjouir d'un succès ou en disposer avant qu'il soit réellement acquis.", exemple: "On n'a pas encore signé le contrat, ne vendons pas la peau de l'ours avant de l'avoir tué." },
  { expression: "Qui vole un œuf vole un bœuf", explication: "Celui qui commet un petit larcin est capable, tôt ou tard, d'en commettre un bien plus grave.", exemple: "Ses parents l'ont sévèrement puni pour ce petit vol : qui vole un œuf vole un bœuf." },
  { expression: "Il ne faut pas réveiller le chat qui dort", explication: "Il vaut mieux ne pas raviver un problème ou un conflit qui s'est apaisé.", exemple: "Ne lui reparle pas de cette histoire, il ne faut pas réveiller le chat qui dort." },
  { expression: "Avoir un œuf à peler avec quelqu'un", explication: "Avoir un différend, une affaire à régler avec quelqu'un.", exemple: "J'ai un œuf à peler avec lui depuis notre dernière réunion." },
  { expression: "Ne pas y aller de main morte", explication: "Agir ou s'exprimer avec beaucoup de force, sans aucun ménagement.", exemple: "Pour cette critique, le journaliste n'y est pas allé de main morte." },
  { expression: "Avoir le diable au corps", explication: "Être extrêmement turbulent, plein d'énergie ou de malice.", exemple: "Ce gamin a le diable au corps, impossible de le tenir en place." },
  { expression: "Faire feu des quatre fers", explication: "Se démener avec une grande énergie pour parvenir à un résultat.", exemple: "Il a fait feu des quatre fers pour boucler le dossier à temps." },
  { expression: "Battre la campagne", explication: "Tenir des propos incohérents, divaguer.", exemple: "Avec la fièvre, il s'est mis à battre la campagne toute la nuit." },
  { expression: "Prendre le mors aux dents", explication: "S'emballer brusquement, agir avec fougue sans plus se contenir.", exemple: "Une fois lancé dans son discours, il a pris le mors aux dents." },
  { expression: "Courir deux lièvres à la fois", explication: "Vouloir mener deux choses en même temps, au risque de ne réussir ni l'une ni l'autre.", exemple: "Il veut monter son entreprise tout en gardant son emploi : on ne court pas deux lièvres à la fois." },
  { expression: "Jeter le manche après la cognée", explication: "Abandonner complètement par découragement, après un échec.", exemple: "Après ce revers, il a bien failli jeter le manche après la cognée." },
  { expression: "Se faire tirer l'oreille", explication: "Se faire prier longuement avant d'accepter de faire quelque chose.", exemple: "Il s'est fait tirer l'oreille avant d'accepter de nous aider." },
  { expression: "Faire flèche de tout bois", explication: "Utiliser tous les moyens disponibles, même les plus improbables, pour parvenir à ses fins.", exemple: "Pour financer son projet, elle a fait flèche de tout bois." },
  { expression: "Ne pas avoir inventé la poudre", explication: "Ne pas être très intelligent ou perspicace.", exemple: "Il est gentil, mais il n'a clairement pas inventé la poudre." },
  { expression: "Prendre quelqu'un à rebrousse-poil", explication: "Aborder quelqu'un ou une situation de la mauvaise manière, à contre-courant de ses habitudes.", exemple: "En lui demandant ça si tôt le matin, tu l'as pris à rebrousse-poil." },
  { expression: "Faire des pieds et des mains", explication: "Se donner beaucoup de mal, employer tous les moyens pour obtenir quelque chose.", exemple: "Elle a fait des pieds et des mains pour obtenir ce poste." },
  { expression: "Tirer à hue et à dia", explication: "Agir dans des directions opposées, sans aucune coordination.", exemple: "Dans cette équipe, chacun tire à hue et à dia, rien n'avance." },
  { expression: "Avoir un pied dans la tombe", explication: "Être très âgé ou très malade, proche de la mort.", exemple: "Le vieil homme plaisantait en disant qu'il avait déjà un pied dans la tombe." },
  { expression: "Se ronger les sangs", explication: "Se faire énormément de souci, s'inquiéter intensément.", exemple: "Elle se ronge les sangs depuis qu'il n'a pas donné de nouvelles." },
  { expression: "Ne pas casser trois pattes à un canard", explication: "N'avoir rien d'exceptionnel, être plutôt médiocre.", exemple: "Son dernier film ne casse pas trois pattes à un canard." },
  { expression: "Prendre la tangente", explication: "S'esquiver discrètement d'une situation, éviter une difficulté.", exemple: "Dès qu'on a parlé du problème, il a pris la tangente." },
  { expression: "Avoir une dent contre quelqu'un", explication: "Garder une rancune envers quelqu'un.", exemple: "Depuis cette histoire, elle a une dent contre son ancien associé." },
  { expression: "Se mettre la rate au court-bouillon", explication: "Se faire beaucoup de souci, s'inquiéter à l'excès (expression régionale).", exemple: "Ne te mets pas la rate au court-bouillon pour si peu." },
  { expression: "Chercher la petite bête", explication: "Être exagérément pointilleux, chercher le moindre défaut.", exemple: "Il relit chaque phrase en cherchant la petite bête." },
  { expression: "Avoir du chien", explication: "Avoir du charme, une allure séduisante malgré des imperfections.", exemple: "Elle n'est pas d'une beauté classique, mais elle a du chien." },
  { expression: "Ne pas y aller avec le dos de la cuillère", explication: "Agir ou parler sans retenue, en exagérant largement.", exemple: "Pour son discours d'adieu, il n'y est pas allé avec le dos de la cuillère." },
  { expression: "Avoir des lettres", explication: "Être cultivé, avoir une solide connaissance de la littérature.", exemple: "On sent tout de suite qu'il a des lettres, rien qu'à sa façon de parler." },
  { expression: "Rendre son tablier", explication: "Démissionner, abandonner volontairement ses fonctions.", exemple: "Après ce désaccord avec la direction, elle a rendu son tablier." },
  { expression: "Avoir la bougeotte", explication: "Ne pas tenir en place, aimer beaucoup se déplacer.", exemple: "Depuis son voyage, il a la bougeotte et ne pense qu'à repartir." },
  { expression: "Prendre ses cliques et ses claques", explication: "Partir précipitamment en emportant toutes ses affaires.", exemple: "Furieux, il a pris ses cliques et ses claques et il est parti." },
  { expression: "Vivre aux crochets de quelqu'un", explication: "Vivre entièrement aux frais d'une autre personne.", exemple: "À trente ans, il vit encore aux crochets de ses parents." },
  { expression: "Avoir un cheveu sur la langue", explication: "Zézayer légèrement en parlant.", exemple: "Il a un léger cheveu sur la langue, on le reconnaît tout de suite au téléphone." },
  { expression: "Se faire des idées", explication: "S'imaginer une situation différente de la réalité, souvent à tort.", exemple: "Rassure-toi, tu te fais des idées, personne ne t'en veut." },
  { expression: "Ne pas être né de la dernière pluie", explication: "Avoir de l'expérience, ne pas être naïf ou facile à tromper.", exemple: "Il n'est pas né de la dernière pluie, il a tout de suite compris la manœuvre." },
  { expression: "Faire l'école buissonnière", explication: "Manquer volontairement l'école sans autorisation.", exemple: "Ils ont fait l'école buissonnière pour aller à la plage." },
  { expression: "Chanter comme une casserole", explication: "Chanter très mal, faux.", exemple: "Il adore le karaoké, même s'il chante comme une casserole." },
  { expression: "Avoir une araignée au plafond", explication: "Être un peu fou, avoir un comportement étrange.", exemple: "Avec ses idées bizarres, on dirait qu'il a une araignée au plafond." },
  { expression: "Mettre la main à la poche", explication: "Accepter de dépenser de l'argent, souvent à contrecœur.", exemple: "Pour ce cadeau collectif, il a fallu que tout le monde mette la main à la poche." },
  { expression: "Prendre le taureau par les cornes", explication: "Affronter un problème de front, avec détermination.", exemple: "Plutôt que d'attendre, elle a décidé de prendre le taureau par les cornes." },
  { expression: "Ne pas valoir un clou", explication: "N'avoir aucune valeur, être sans intérêt.", exemple: "Cet outil bon marché ne vaut pas un clou." },
  { expression: "Avoir plus d'un tour dans son sac", explication: "Être rusé, disposer de plusieurs solutions ou astuces en réserve.", exemple: "Ne t'inquiète pas pour lui, il a toujours plus d'un tour dans son sac." },
  { expression: "Filer doux", explication: "Obéir sans protester, se montrer soumis.", exemple: "Depuis la remarque du chef, il file doux." },
  { expression: "Avoir maille à partir avec la justice", explication: "Avoir des ennuis, un différend avec les autorités judiciaires.", exemple: "Son cousin a eu maille à partir avec la justice il y a quelques années." },
  { expression: "Manger de la vache enragée", explication: "Traverser une période de grande pauvreté ou de grandes difficultés.", exemple: "Au début de sa carrière, il a mangé de la vache enragée avant de réussir." },
  { expression: "Se croire sorti de la cuisse de Jupiter", explication: "Se juger d'une importance ou d'une origine supérieure aux autres, avec prétention.", exemple: "Depuis sa promotion, il se croit sorti de la cuisse de Jupiter." },
  { expression: "Avoir le bec dans l'eau", explication: "Rester dans l'incertitude ou l'attente, sans obtenir de réponse.", exemple: "Après sa demande sans réponse, il est resté le bec dans l'eau." },
];
