// Chaque entrée : une expression, son explication et une phrase d'exemple.
// Pour enrichir le carnet, il suffit d'ajouter un objet au tableau ci-dessous.
const EXPRESSIONS = [
  { expression: "Poser un lapin", explication: "Ne pas se présenter à un rendez-vous, sans prévenir la personne qui attend.", exemple: "Il m'a posé un lapin hier soir, je l'ai attendu une heure au café." },
  { expression: "Avoir le cafard", explication: "Être triste, un peu déprimé, sans raison précise.", exemple: "Depuis qu'il pleut sans arrêt, j'ai un peu le cafard." },
  { expression: "Casser du sucre sur le dos de quelqu'un", explication: "Dire du mal de quelqu'un en son absence.", exemple: "Arrête de casser du sucre sur son dos, ce n'est pas très correct." },
  { expression: "Chercher midi à quatorze heures", explication: "Compliquer inutilement une chose simple.", exemple: "Ne cherche pas midi à quatorze heures, la réponse est juste devant toi." },
  { expression: "Avoir un chat dans la gorge", explication: "Avoir la voix enrouée, avoir du mal à parler clairement.", exemple: "Excuse-moi, j'ai un chat dans la gorge ce matin." },
  { expression: "Filer à l'anglaise", explication: "Partir discrètement, sans dire au revoir à personne.", exemple: "Il a filé à l'anglaise avant la fin de la soirée." },
  { expression: "Mettre son grain de sel", explication: "Donner son avis sur un sujet sans qu'on le lui ait demandé.", exemple: "Il faut toujours qu'elle mette son grain de sel dans nos conversations." },
  { expression: "Coûter les yeux de la tête", explication: "Être extrêmement cher.", exemple: "Cette voiture coûte les yeux de la tête." },
  { expression: "Avoir la pêche", explication: "Être plein d'énergie, se sentir en pleine forme.", exemple: "Ce matin j'ai la pêche, j'ai vraiment bien dormi." },
  { expression: "Tomber dans les pommes", explication: "S'évanouir.", exemple: "Elle est tombée dans les pommes à cause de la chaleur." },
  { expression: "Raconter des salades", explication: "Mentir, inventer des histoires peu crédibles.", exemple: "Ne l'écoute pas, il raconte encore des salades." },
  { expression: "Avoir un poil dans la main", explication: "Être particulièrement paresseux.", exemple: "Il a un poil dans la main, il ne fait jamais rien à la maison." },
  { expression: "Donner sa langue au chat", explication: "Renoncer à deviner une réponse et demander qu'on la révèle.", exemple: "Je donne ma langue au chat, quelle est la réponse ?" },
  { expression: "Il pleut des cordes", explication: "Il pleut très fort, abondamment.", exemple: "Prends un parapluie, il pleut des cordes dehors." },
  { expression: "Avoir d'autres chats à fouetter", explication: "Avoir des préoccupations plus importantes ou plus urgentes.", exemple: "Je n'ai pas le temps de m'en occuper, j'ai d'autres chats à fouetter." },
  { expression: "Mettre la charrue avant les bœufs", explication: "Faire les choses dans le désordre, précipiter une étape avant l'autre.", exemple: "On ne peut pas signer avant d'avoir le budget, ce serait mettre la charrue avant les bœufs." },
  { expression: "Être dans de beaux draps", explication: "Se trouver dans une situation difficile ou embarrassante.", exemple: "Avec toutes ces dettes, il est dans de beaux draps." },
  { expression: "Avoir le bras long", explication: "Avoir de l'influence ou des relations utiles.", exemple: "Il a le bras long dans cette entreprise, il connaît tout le monde." },
  { expression: "Passer une nuit blanche", explication: "Ne pas dormir du tout pendant la nuit.", exemple: "J'ai passé une nuit blanche à réviser pour l'examen." },
  { expression: "Se prendre un râteau", explication: "Essuyer un refus, en particulier dans le domaine amoureux.", exemple: "Il lui a proposé de sortir avec lui, mais il s'est pris un râteau." },
  { expression: "Avoir la moutarde qui monte au nez", explication: "Commencer à s'énerver, sentir la colère arriver.", exemple: "Quand il a menti devant tout le monde, j'ai senti la moutarde me monter au nez." },
  { expression: "Rouler quelqu'un dans la farine", explication: "Tromper quelqu'un, le duper.", exemple: "Ce vendeur t'a roulé dans la farine avec ce prix." },
  { expression: "Ne pas être dans son assiette", explication: "Ne pas se sentir bien, physiquement ou moralement.", exemple: "Tu es pâle, tu n'as pas l'air dans ton assiette aujourd'hui." },
  { expression: "Avoir un coup de foudre", explication: "Tomber amoureux instantanément.", exemple: "Ils ont eu un coup de foudre en se rencontrant à la fac." },
  { expression: "Mettre les pieds dans le plat", explication: "Aborder un sujet délicat sans aucun tact.", exemple: "Il a encore mis les pieds dans le plat en posant cette question." },
  { expression: "Faire la grasse matinée", explication: "Dormir tard, prolonger la matinée au lit.", exemple: "Le dimanche, j'aime faire la grasse matinée." },
  { expression: "Avoir les yeux plus gros que le ventre", explication: "Se servir plus qu'on ne peut manger, ou être trop ambitieux.", exemple: "Il a pris trois desserts, il a vraiment les yeux plus gros que le ventre." },
  { expression: "Jeter l'éponge", explication: "Abandonner, renoncer à continuer.", exemple: "Après trois échecs, il a fini par jeter l'éponge." },
  { expression: "Ne pas y aller par quatre chemins", explication: "Être direct, franc, sans détour.", exemple: "Je ne vais pas y aller par quatre chemins : ton projet ne marche pas." },
  { expression: "Tirer les vers du nez", explication: "Faire parler quelqu'un par des questions habiles, lui soutirer des informations.", exemple: "Elle a réussi à lui tirer les vers du nez sur son secret." },
  { expression: "Être sur son trente-et-un", explication: "Être très élégamment habillé.", exemple: "Pour le mariage, elle était sur son trente-et-un." },
  { expression: "Avoir la tête dans les nuages", explication: "Être distrait, rêveur, peu attentif à la réalité.", exemple: "Concentre-toi un peu, tu as toujours la tête dans les nuages." },
  { expression: "Casser sa pipe", explication: "Mourir (registre familier).", exemple: "Le vieux chat du voisin a cassé sa pipe la semaine dernière." },
  { expression: "Mettre du beurre dans les épinards", explication: "Améliorer légèrement sa situation financière.", exemple: "Ce petit boulot du week-end met du beurre dans les épinards." },
  { expression: "Faire d'une pierre deux coups", explication: "Réaliser deux choses en une seule action.", exemple: "En allant au marché, j'ai fait d'une pierre deux coups : les courses et la promenade." },
  { expression: "Traîner des pieds", explication: "Agir avec réticence et lenteur, montrer peu d'enthousiasme.", exemple: "Il traîne des pieds pour rendre son rapport." },
  { expression: "Avoir le cœur sur la main", explication: "Être généreux, toujours prêt à aider les autres.", exemple: "Elle a le cœur sur la main, elle aide tout le monde sans compter." },
  { expression: "Passer l'éponge", explication: "Pardonner une faute, décider de l'oublier.", exemple: "Cette fois, je passe l'éponge, mais ne recommence pas." },
  { expression: "Se faire des cheveux blancs", explication: "Se faire beaucoup de souci pour quelqu'un ou quelque chose.", exemple: "Avec ses résultats scolaires, ses parents se font des cheveux blancs." },
  { expression: "Voir midi à sa porte", explication: "Juger toute chose selon son propre point de vue, sans considérer celui des autres.", exemple: "Il voit midi à sa porte, il ne comprend jamais le point de vue des autres." },
  { expression: "Être haut comme trois pommes", explication: "Être très petit, généralement en parlant d'un enfant.", exemple: "Il était haut comme trois pommes quand je l'ai connu." },
  { expression: "Avoir la banane", explication: "Sourire, être de bonne humeur.", exemple: "Elle a la banane depuis qu'elle a eu son diplôme." },
  { expression: "Manger sur le pouce", explication: "Manger rapidement, sans prendre le temps de s'installer.", exemple: "À midi, je mange souvent sur le pouce entre deux réunions." },
  { expression: "Avoir du pain sur la planche", explication: "Avoir beaucoup de travail à accomplir.", exemple: "Avant les vacances, j'ai encore du pain sur la planche." },
  { expression: "Faire la tête", explication: "Bouder, être de mauvaise humeur envers quelqu'un.", exemple: "Depuis notre dispute, il me fait la tête." },
  { expression: "Prendre ses jambes à son cou", explication: "S'enfuir en courant, très rapidement.", exemple: "En voyant le chien, il a pris ses jambes à son cou." },
  { expression: "Mettre la main à la pâte", explication: "Participer activement à une tâche, s'impliquer concrètement.", exemple: "Pour préparer le repas de famille, tout le monde met la main à la pâte." },
  { expression: "Avoir le compas dans l'œil", explication: "Évaluer une distance ou une mesure avec précision, sans instrument.", exemple: "Le menuisier a le compas dans l'œil, il ne se trompe presque jamais." },
  { expression: "Vendre la mèche", explication: "Révéler un secret que l'on devait garder.", exemple: "C'est lui qui a vendu la mèche à propos de la surprise." },
  { expression: "Faire chou blanc", explication: "Échouer complètement dans une tentative.", exemple: "On a cherché partout pendant des heures, on a fait chou blanc." },
  { expression: "Mettre la clé sous la porte", explication: "Fermer définitivement un commerce ou cesser une activité.", exemple: "Avec la crise, plusieurs petits commerces du quartier ont dû mettre la clé sous la porte." },
  { expression: "Avoir le vent en poupe", explication: "Connaître un grand succès, une dynamique très favorable.", exemple: "Depuis sa dernière collection, cette marque a le vent en poupe." },
  { expression: "Se mettre le doigt dans l'œil", explication: "Se tromper complètement sur un sujet.", exemple: "Si tu penses qu'il va accepter sans négocier, tu te mets le doigt dans l'œil." },
  { expression: "Tourner autour du pot", explication: "Éviter d'aborder directement un sujet, parler par détours.", exemple: "Arrête de tourner autour du pot et dis-moi ce qui ne va pas." },
  { expression: "Avoir la tête sur les épaules", explication: "Être raisonnable, faire preuve de bon sens.", exemple: "Malgré son jeune âge, elle a vraiment la tête sur les épaules." },
  { expression: "Être aux anges", explication: "Être extrêmement heureux, comblé.", exemple: "Depuis qu'il a reçu sa réponse d'admission, il est aux anges." },
  { expression: "Avoir un bœuf sur la langue", explication: "Être contraint de garder le silence sur quelque chose.", exemple: "Il sait très bien ce qui s'est passé, mais il a un bœuf sur la langue." },
  { expression: "Mettre les bouchées doubles", explication: "Accélérer nettement le rythme de travail pour rattraper le temps perdu.", exemple: "Il ne reste que deux jours avant la remise, il va falloir mettre les bouchées doubles." },
  { expression: "Avoir maille à partir avec quelqu'un", explication: "Avoir un différend, des ennuis avec quelqu'un.", exemple: "Il a eu maille à partir avec son voisin à cause du bruit." },
  { expression: "Prendre quelqu'un la main dans le sac", explication: "Surprendre quelqu'un en flagrant délit.", exemple: "Le gardien l'a pris la main dans le sac en train de voler des fournitures." },
  { expression: "Avoir un œil de lynx", explication: "Avoir une vue perçante, remarquer les moindres détails.", exemple: "Rien ne lui échappe, elle a un œil de lynx pour repérer les fautes." },
  { expression: "Mettre tous ses œufs dans le même panier", explication: "Tout miser sur une seule solution, sans répartir les risques.", exemple: "Investir toutes ses économies dans une seule entreprise, c'est mettre tous ses œufs dans le même panier." },
  { expression: "Avoir le dos large", explication: "Accepter facilement d'être blâmé, servir de bouc émissaire.", exemple: "Comme d'habitude, c'est moi qui ai le dos large quand quelque chose ne va pas." },
  { expression: "Ne pas avoir la langue dans sa poche", explication: "Être franc, parler sans retenue ni détour.", exemple: "Elle n'a pas la langue dans sa poche, elle dit toujours ce qu'elle pense." },
  { expression: "Marcher sur des œufs", explication: "Agir avec une extrême prudence dans une situation délicate.", exemple: "Depuis leur dispute, on marche sur des œufs quand on parle d'elle devant lui." },
  { expression: "Avoir le nez creux", explication: "Avoir de l'intuition, deviner juste avant les autres.", exemple: "Il a eu le nez creux en vendant ses actions juste avant la baisse." },
  { expression: "Se mettre en quatre", explication: "Se donner énormément de mal pour aider quelqu'un.", exemple: "Elle s'est mise en quatre pour que la fête soit une réussite." },
  { expression: "Avoir des fourmis dans les jambes", explication: "Ressentir un picotement dans les jambes, ou avoir une forte envie de bouger.", exemple: "Après des heures assis dans le train, j'ai des fourmis dans les jambes." },
  { expression: "Être sur la même longueur d'onde", explication: "Bien se comprendre, partager la même façon de penser.", exemple: "Avec ce collègue, on est toujours sur la même longueur d'onde." },
  { expression: "Prendre la mouche", explication: "Se vexer rapidement, s'énerver pour peu de choses.", exemple: "Il a pris la mouche dès qu'on a critiqué son idée." },
  { expression: "Avoir le cœur gros", explication: "Être triste, ému, avoir du chagrin.", exemple: "Elle avait le cœur gros en quittant sa ville natale." },
  { expression: "Filer un mauvais coton", explication: "Évoluer vers une situation qui se dégrade.", exemple: "Depuis qu'il a changé d'amis, il file un mauvais coton." },
  { expression: "Mettre de l'eau dans son vin", explication: "Modérer ses exigences, faire des concessions.", exemple: "Pour trouver un accord, chacun va devoir mettre un peu d'eau dans son vin." },
  { expression: "Avoir un train de retard", explication: "Être en décalage, ne pas être au courant des dernières nouveautés.", exemple: "En matière de technologie, cette entreprise a toujours un train de retard." },
  { expression: "Se serrer la ceinture", explication: "Réduire ses dépenses, vivre avec peu de moyens.", exemple: "Après cet achat imprévu, on va devoir se serrer la ceinture ce mois-ci." },
  { expression: "Avoir la langue bien pendue", explication: "Être très bavard, parler avec beaucoup de facilité.", exemple: "Il a la langue bien pendue, impossible de placer un mot quand il raconte une histoire." },
  { expression: "Tomber des nues", explication: "Être extrêmement surpris, ne rien avoir vu venir.", exemple: "Quand elle a annoncé son départ, tout le monde est tombé des nues." },
  { expression: "Passer un savon à quelqu'un", explication: "Réprimander vivement quelqu'un.", exemple: "Le directeur lui a passé un savon pour son retard répété." },
  { expression: "Être à côté de la plaque", explication: "Se tromper complètement, ne pas comprendre la situation.", exemple: "Sa réponse était complètement à côté de la plaque." },
  { expression: "Avoir le trac", explication: "Ressentir une forte anxiété avant de se produire en public.", exemple: "Avant chaque concert, elle a le trac pendant les premières minutes." },
  { expression: "Mettre quelqu'un au parfum", explication: "Informer quelqu'un d'une situation, le mettre au courant.", exemple: "Avant la réunion, quelqu'un l'a mis au parfum sur les tensions de l'équipe." },
  { expression: "Rester bouche bée", explication: "Être stupéfait au point de ne plus pouvoir parler.", exemple: "Devant ce paysage, nous sommes restés bouche bée." },
  { expression: "Prendre son courage à deux mains", explication: "Se décider à affronter une situation difficile malgré l'appréhension.", exemple: "Il a pris son courage à deux mains pour annoncer la nouvelle à ses parents." },
  { expression: "Avoir la puce à l'oreille", explication: "Être averti, se douter de quelque chose avant d'en avoir la preuve.", exemple: "Son silence soudain m'a mis la puce à l'oreille." },
  { expression: "Ne pas faire long feu", explication: "Ne pas durer longtemps, échouer rapidement.", exemple: "Ce projet mal préparé n'a pas fait long feu." },
  { expression: "Casser les pieds à quelqu'un", explication: "Importuner, agacer quelqu'un par son insistance.", exemple: "Il nous casse les pieds avec ses questions depuis ce matin." },
  { expression: "Avoir un ticket avec quelqu'un", explication: "Plaire à quelqu'un, ressentir une attirance réciproque.", exemple: "On dirait bien qu'il a un ticket avec la nouvelle stagiaire." },
  { expression: "Se creuser la tête", explication: "Réfléchir intensément pour trouver une solution.", exemple: "Je me creuse la tête depuis une heure pour ce mot croisé." },
  { expression: "Avoir le melon", explication: "Être prétentieux, avoir une trop haute opinion de soi-même.", exemple: "Depuis son succès, il a un peu le melon." },
  { expression: "Rouler sa bosse", explication: "Beaucoup voyager, accumuler de l'expérience au fil des années.", exemple: "Il a roulé sa bosse dans plusieurs pays avant de revenir s'installer ici." },
  { expression: "Mettre les points sur les i", explication: "Clarifier une situation avec précision, sans laisser d'ambiguïté.", exemple: "Il est temps de mettre les points sur les i avant de continuer ce projet ensemble." },
  { expression: "Avoir le dernier mot", explication: "L'emporter dans une discussion, avoir raison en dernier lieu.", exemple: "Avec elle, c'est difficile d'avoir le dernier mot." },
  { expression: "Passer du coq à l'âne", explication: "Changer brusquement de sujet de conversation, sans transition.", exemple: "Il passe sans cesse du coq à l'âne, difficile de suivre son raisonnement." },
  { expression: "Être né sous une bonne étoile", explication: "Avoir de la chance tout au long de sa vie.", exemple: "Il a toujours réussi sans effort, on dirait qu'il est né sous une bonne étoile." },
  { expression: "Ne pas faire dans la dentelle", explication: "Agir sans délicatesse ni retenue.", exemple: "Pour cette négociation, il n'a pas fait dans la dentelle." },
  { expression: "Avoir des atomes crochus avec quelqu'un", explication: "Bien s'entendre naturellement avec quelqu'un, dès le début.", exemple: "On a eu des atomes crochus dès notre première rencontre." },
  { expression: "Avoir le bourdon", explication: "Être triste, avoir un coup de cafard passager.", exemple: "Ce dimanche pluvieux lui a donné le bourdon." },
  { expression: "Se mettre martel en tête", explication: "Se faire du souci, s'inquiéter excessivement pour quelque chose.", exemple: "Ne te mets pas martel en tête, tout va s'arranger." },
  { expression: "Avoir voix au chapitre", explication: "Avoir le droit de donner son avis dans une décision.", exemple: "Sur ce dossier, les employés ont enfin voix au chapitre." },
  { expression: "Faire la pluie et le beau temps", explication: "Avoir une grande influence, décider de tout dans un domaine.", exemple: "Dans cette entreprise, c'est lui qui fait la pluie et le beau temps." },
];
