// Chaque entrée : un mot, sa nature grammaticale, sa définition et une phrase d'exemple.
// Pour enrichir le carnet, il suffit d'ajouter un objet au tableau ci-dessous.
const MOTS = [
  { mot: "Idoine", nature: "adj.", definition: "Qui convient parfaitement à une situation, approprié.", exemple: "Ce lieu est idoine pour organiser la réception." },
  { mot: "Abscons", nature: "adj.", definition: "Difficile à comprendre, obscur.", exemple: "Son discours était trop abscons pour l'auditoire." },
  { mot: "Dystopie", nature: "n.f.", definition: "Récit dépeignant une société future oppressive, l'inverse d'une utopie.", exemple: "Ce roman décrit une dystopie où toute vie privée a disparu." },
  { mot: "Pléonasme", nature: "n.m.", definition: "Répétition inutile d'une idée déjà exprimée dans la même phrase.", exemple: "\"Monter en haut\" est un pléonasme courant." },
  { mot: "Sibyllin", nature: "adj.", definition: "Mystérieux, dont le sens est difficile à saisir.", exemple: "Sa réponse sibylline n'a éclairci personne." },
  { mot: "Ubuesque", nature: "adj.", definition: "Grotesque et absurde jusqu'au ridicule.", exemple: "La situation administrative était devenue ubuesque." },
  { mot: "Fatuité", nature: "n.f.", definition: "Vanité, suffisance ridicule.", exemple: "Il parle de ses succès avec une fatuité agaçante." },
  { mot: "Palabre", nature: "n.f.", definition: "Longue discussion, souvent stérile.", exemple: "Ils ont passé la soirée en palabres sans rien décider." },
  { mot: "Acabit", nature: "n.m.", definition: "Genre, nature de quelqu'un ou quelque chose (souvent péjoratif).", exemple: "Je me méfie des gens de cet acabit." },
  { mot: "Byzantin", nature: "adj.", definition: "Relatif à des discussions subtiles et compliquées à l'excès.", exemple: "Ces querelles byzantines n'intéressent plus personne." },
  { mot: "Circonlocution", nature: "n.f.", definition: "Façon détournée de dire quelque chose, périphrase.", exemple: "Il a annoncé son licenciement par une longue circonlocution." },
  { mot: "Cacophonie", nature: "n.f.", definition: "Mélange de sons discordants et désagréables.", exemple: "Les klaxons formaient une véritable cacophonie." },
  { mot: "Loquace", nature: "adj.", definition: "Qui parle beaucoup, bavard.", exemple: "Il est rarement aussi loquace qu'aujourd'hui." },
  { mot: "Pusillanime", nature: "adj.", definition: "Qui manque de courage, craintif face aux difficultés.", exemple: "Sa réaction pusillanime a déçu ses collègues." },
  { mot: "Nonchalance", nature: "n.f.", definition: "Attitude détachée, sans énergie apparente.", exemple: "Il a répondu avec une grande nonchalance." },
  { mot: "Truculent", nature: "adj.", definition: "Pittoresque et haut en couleur, souvent avec verve.", exemple: "Son langage truculent amusait toute la table." },
  { mot: "Vétilleux", nature: "adj.", definition: "Qui s'attache à des détails insignifiants.", exemple: "Le professeur est vétilleux sur la ponctuation." },
  { mot: "Prolixe", nature: "adj.", definition: "Qui s'exprime avec trop de mots, verbeux.", exemple: "Son rapport est prolixe, on pourrait le résumer en deux pages." },
  { mot: "Ostracisme", nature: "n.m.", definition: "Exclusion volontaire d'un groupe, mise à l'écart.", exemple: "Il a subi l'ostracisme de ses anciens collègues." },
  { mot: "Pérorer", nature: "v.", definition: "Parler longuement et avec emphase, souvent avec prétention.", exemple: "Il a péroré pendant une heure sans laisser parler personne." },
  { mot: "Fallacieux", nature: "adj.", definition: "Trompeur, qui repose sur une erreur volontaire.", exemple: "Son argument fallacieux n'a convaincu personne." },
  { mot: "Anachronique", nature: "adj.", definition: "Qui appartient à une autre époque, décalé dans le temps.", exemple: "Cette règle paraît totalement anachronique aujourd'hui." },
  { mot: "Concomitant", nature: "adj.", definition: "Qui se produit en même temps qu'un autre événement.", exemple: "La hausse des prix a été concomitante à la pénurie." },
  { mot: "Éphémère", nature: "adj.", definition: "Qui dure très peu de temps.", exemple: "Leur succès fut éphémère." },
  { mot: "Idiosyncrasie", nature: "n.f.", definition: "Ensemble des particularités propres à une personne.", exemple: "Chaque écrivain a son idiosyncrasie stylistique." },
  { mot: "Circonspect", nature: "adj.", definition: "Prudent, qui agit avec réflexion et précaution.", exemple: "Face à cette offre, il est resté circonspect." },
  { mot: "Périphrase", nature: "n.f.", definition: "Expression qui remplace un mot par une formule plus longue.", exemple: "\"La ville lumière\" est une périphrase pour désigner Paris." },
  { mot: "Impétueux", nature: "adj.", definition: "Qui agit avec fougue et impulsivité.", exemple: "Son caractère impétueux lui joue parfois des tours." },
  { mot: "Nébuleux", nature: "adj.", definition: "Vague, peu clair, difficile à cerner.", exemple: "Son projet reste encore assez nébuleux." },
  { mot: "Suranné", nature: "adj.", definition: "Qui n'est plus d'usage, démodé.", exemple: "Ce vocabulaire suranné amuse les plus jeunes." },
  { mot: "Bigarré", nature: "adj.", definition: "Composé de couleurs ou d'éléments très variés.", exemple: "La foule bigarrée envahissait les rues du marché." },
  { mot: "Volubile", nature: "adj.", definition: "Qui parle avec abondance et rapidité.", exemple: "Elle est restée volubile durant tout l'entretien." },
  { mot: "Insidieux", nature: "adj.", definition: "Qui agit de façon sournoise, dangereux sans en avoir l'air.", exemple: "La maladie a progressé de manière insidieuse." },
  { mot: "Kafkaïen", nature: "adj.", definition: "Absurde et oppressant, à la manière des situations décrites par Kafka.", exemple: "Cette procédure administrative est kafkaïenne." },
  { mot: "Latitude", nature: "n.f.", definition: "Au sens figuré, liberté d'action laissée à quelqu'un.", exemple: "On lui a laissé une grande latitude pour organiser le projet." },
  { mot: "Mansuétude", nature: "n.f.", definition: "Indulgence, bienveillance envers les fautes d'autrui.", exemple: "Le juge a fait preuve de mansuétude envers le jeune accusé." },
  { mot: "Obséquieux", nature: "adj.", definition: "Excessivement poli et flatteur, par intérêt.", exemple: "Le vendeur se montrait obséquieux avec les clients fortunés." },
  { mot: "Panacée", nature: "n.f.", definition: "Remède ou solution universelle censée tout résoudre.", exemple: "Ce logiciel n'est pas la panacée à tous les problèmes de l'entreprise." },
  { mot: "Quiproquo", nature: "n.m.", definition: "Malentendu où une personne ou une chose est prise pour une autre.", exemple: "Toute la scène du film repose sur un quiproquo." },
  { mot: "Récalcitrant", nature: "adj.", definition: "Qui résiste, refuse d'obéir.", exemple: "Le chien restait récalcitrant malgré les ordres." },
  { mot: "Sempiternel", nature: "adj.", definition: "Qui revient sans cesse, éternel de façon lassante.", exemple: "Il se plaint encore de son sempiternel problème de voisinage." },
  { mot: "Taciturne", nature: "adj.", definition: "Qui parle peu, silencieux par tempérament.", exemple: "Depuis l'accident, il est devenu taciturne." },
  { mot: "Vindicatif", nature: "adj.", definition: "Porté à se venger, rancunier.", exemple: "Elle a un caractère vindicatif, elle n'oublie jamais une offense." },
  { mot: "Zélé", nature: "adj.", definition: "Qui montre un empressement excessif dans son travail.", exemple: "Le nouvel employé, trop zélé, agace déjà ses collègues." },
  { mot: "Éculé", nature: "adj.", definition: "Usé à force d'avoir servi, devenu banal.", exemple: "Cette blague est vraiment éculée." },
  { mot: "Iconoclaste", nature: "adj./n.", definition: "Qui rejette les traditions et les idées établies.", exemple: "Cet artiste iconoclaste bouscule les codes académiques." },
  { mot: "Larvé", nature: "adj.", definition: "Qui existe de façon cachée, sans se manifester ouvertement.", exemple: "Un conflit larvé opposait les deux services depuis des mois." },
  { mot: "Maussade", nature: "adj.", definition: "De mauvaise humeur, morose, ou terne pour le temps qu'il fait.", exemple: "Le ciel maussade annonçait une journée pluvieuse." },
  { mot: "Opiniâtre", nature: "adj.", definition: "Qui persévère avec une grande obstination.", exemple: "Grâce à ses efforts opiniâtres, il a fini par réussir." },
  { mot: "Pléthore", nature: "n.f.", definition: "Grande abondance, excès de quantité.", exemple: "Il y avait une pléthore de candidats pour ce poste." },
];
